#pragma once

// generated by sqlite2cpp.py ddl.txt src/db trees

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace trees
{
  namespace Blocks_
  {
    struct BlockId
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "block_id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T blockId;
            T& operator()() { return blockId; }
            const T& operator()() const { return blockId; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct LabelSize
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "label_size";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T labelSize;
            T& operator()() { return labelSize; }
            const T& operator()() const { return labelSize; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
    struct SetStr
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "set_str";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T setStr;
            T& operator()() { return setStr; }
            const T& operator()() const { return setStr; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
  } // namespace Blocks_

  struct Blocks: sqlpp::table_t<Blocks,
               Blocks_::BlockId,
               Blocks_::LabelSize,
               Blocks_::SetStr>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "blocks";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T blocks;
        T& operator()() { return blocks; }
        const T& operator()() const { return blocks; }
      };
    };
  };
  namespace Trees_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct Branches
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "branches";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T branches;
            T& operator()() { return branches; }
            const T& operator()() const { return branches; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct Degrees
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "degrees";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T degrees;
            T& operator()() { return degrees; }
            const T& operator()() const { return degrees; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::text, sqlpp::tag::require_insert>;
    };
    struct LabelSize
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "label_size";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T labelSize;
            T& operator()() { return labelSize; }
            const T& operator()() const { return labelSize; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer>;
    };
  } // namespace Trees_

  struct Trees: sqlpp::table_t<Trees,
               Trees_::Id,
               Trees_::Branches,
               Trees_::Degrees,
               Trees_::LabelSize>
  {
    struct _alias_t
    {
      static constexpr const char _literal[] =  "trees";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T trees;
        T& operator()() { return trees; }
        const T& operator()() const { return trees; }
      };
    };
  };
} // namespace trees
